# Generated by Django 5.2 on 2025-05-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('official_name', models.CharField(max_length=255)),
                ('cca2', models.CharField(max_length=2, unique=True)),
                ('cca3', models.CharField(max_length=3, unique=True)),
                ('flag', models.URLField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.BigIntegerField()),
                ('languages', models.JSONField(blank=True, default=dict, null=True)),
                ('timezones', models.JSONField(blank=True, default=list, null=True)),
                ('capitals', models.JSONField(blank=True, default=list, null=True)),
                ('currencies', models.JSONField(blank=True, default=dict, null=True)),
                ('borders', models.JSONField(blank=True, default=list, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
    ]
