# Generated by Django 5.2 on 2025-05-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries_api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['region'], name='countries_a_region_0c4425_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['languages'], name='countries_a_languag_a79839_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['borders'], name='countries_a_borders_c36b63_idx'),
        ),
    ]
